机器学习主要分为四大类：监督学习(Supervised Learning)，半监督学习(Semi-supervised Learning)，无监督学习(Unsupervised Learning)，强化学习(Reinforcement Learning)

监督学习
概念：我们在训练这些模型的时候，给它的数据里面不仅有题目（特征），还有标准答案（标签）

特征是你用来描述一个事物的属性、指标或者是数据点
比如：当你向朋友描述一个人时，你会说“他身高1米8，戴眼镜，喜欢打篮球”。这里的“身高”、“是否戴眼镜”、“爱好”就是这个人的特征。
在机器学习中，特征通常被写成大写字母X，因为特征往往不止一个，他们组合在一起会形成一个”数据矩阵“（二维表格）

标签是你希望模型最终预测出来的结果。
在模型训练阶段，标签就是提供给模型的”标准答案“，让它知道自己猜的对不对。
比如：接上面的例子，如果你描述了那个人的特征，最后让你朋友猜“这人是程序员还是健身教练？”，那么“职业”就是你要预测的标签。
标签通常被写成字母y，因为对于每个事物来说，我们要预测的结果通常只有一个（比如房价是多少，是否有病），它在数据中通常只是一列数字

总之，特征就是一个事物的属性或者是特点（比如游戏本，特征是笨重，性能好，续航差）；标签就是我们希望模型能根据已知的数据，能给出预期的判断或者是数值答案（“分类”标签和“回归”标签）

在scikit-learn的工作流中，拿到数据后的第一件事，就是把数据拆分成复习资料（训练集）、模拟考（验证集）和考卷（测试集）
所对应的函数就是train_test_split

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

# 重量，性能跑分，续航时长h
X = np.array([
    [3.5, 15000, 2.0],  # 电脑 A (游戏本)
    [1.2,  4000, 10.0], # 电脑 B (轻薄本)
    [2.8, 12000, 3.5],  # 电脑 C (全能本)
    [3.2, 16000, 1.5],  # 电脑 D (游戏本)
    [1.0,  3500, 12.0]  # 电脑 E (轻薄本)
])

y = np.array([1, 0, 0, 1, 0])


# ================= 第一步：分出绝对保密的“期末考” =================
# 我们把全部数据切开：80% 留作平时用(X_temp)，20% 锁进保险柜作为期末考(X_test)
# test_size=0.2 的意思是把20%的数据留作测试（考卷），80% 用来训练（复习）
# random_state=42 就像是游戏里的“固定存档”（种子数），保证每次运行拆分的结果都是一样的
# X_train, X_test, y_train, y_test 的顺序定死，千万不能更改顺序
# shuffle 关键词布尔值，True，打乱数据（默认）；False，不打乱数据
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# ================= 第二步：把平时用的数据分成“作业”和“模拟考” =================
# 注意这里的数学逻辑：我们要从剩下的 80% (temp) 里切出 25%。
# 因为 80% * 25% = 20%，这样刚好分出了占总数据 20% 的验证集
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.25, random_state=42)

print("给模型复习用的特征（X_train）：")
print(X_train)
print("\n给模型模拟考用的特征（X_val）：")
print(X_val)
print("\n留作考试用的特征(X_test)：")
print(X_test)

'''
给模型复习用的特征（X_train）：
[[3.2e+00 1.6e+04 1.5e+00]
 [1.0e+00 3.5e+03 1.2e+01]
 [3.5e+00 1.5e+04 2.0e+00]]

给模型模拟考用的特征（X_val）：
[[2.8e+00 1.2e+04 3.5e+00]]

留作考试用的特征(X_test)：
[[1.2e+00 4.0e+03 1.0e+01]]

这种输出结果是科学计数法（为了使排版整齐）
在编程中，e+03就代表e前面的这个数乘以10^3（也就是1000），e+00就是乘以10^0（也就是1，保持不变）
例如：
1.2e+00 = 1.2 x 10^0 = 1.2
4.0e+03 = 4.0 x 10^3 = 4000

将原来的数据集顺序打乱，然后按照test_size分配给训练、验证和测试
'''

给模型复习用的特征（X_train）：
[[3.2e+00 1.6e+04 1.5e+00]
 [1.0e+00 3.5e+03 1.2e+01]
 [3.5e+00 1.5e+04 2.0e+00]]

给模型模拟考用的特征（X_val）：
[[2.8e+00 1.2e+04 3.5e+00]]

留作考试用的特征(X_test)：
[[1.2e+00 4.0e+03 1.0e+01]]


'\n给模型复习用的特征（X_train）：\n[[1.0e+00 3.5e+03 1.2e+01]\n [2.8e+00 1.2e+04 3.5e+00]\n [3.5e+00 1.5e+04 2.0e+00]\n [3.2e+00 1.6e+04 1.5e+00]]\n\n留作考试用的特征(X_test)：\n[[1.2e+00 4.0e+03 1.0e+01]]\n\n这种输出结果是科学计数法（为了使排版整齐）\n在编程中，e+03就代表e前面的这个数乘以10^3（也就是1000），e+00就是乘以10^0（也就是1，保持不变）\n例如：\n1.2e+00 = 1.2 x 10^0 = 1.2\n4.0e+03 = 4.0 x 10^3 = 4000\n\n将原来的数据集顺序打乱，然后按照test_size分配给训练和测试\n'

验证集的最重要作用就是调参（寻找最佳超参数）  
（调参请看HPO.ipynb文件）  
  
验证集(Validation Set)  
是指在模型训练过程中，从原始数据中拨出来的一份独立数据，他不参与模型的直接参数计算和训练，专门用于评估模型在未见数据上的表现（也就是泛化能力(Generalization Ability)），并据此进行超参数优化  
如果不设验证集，直接用测试集来调整模型，就会发生极其严重的“数据泄露(Data Leakage)”。这意味着模型虽然在测试集上分数很高，但那是根据测试集测出来的判断结果修改超参数得到的，如果换一个测试集，就会导致模型在真实场景下的泛化表现大打折扣  
换句话说，机器学习的本质，就是让机器在已知的数据中，去解决未知的问题。将验证集和测试集分开，就是为了让机器在已知（训练集）中，去解决未知（测试集）的问题，而模型训练中，需要人为干预，也就是调参，验证集就是干这个用的。  
比如：  
一名学生（模型），平时通过刷题（用训练集训练模型）来增强做题能力，然后学校会举行模拟考试（验证集），并且会告诉学生哪里做对了，哪里做错了，给予反馈（调参），然后学生就会再接着刷题（训练），学生再接着参加模拟考试，以此循环类推，最后学生参加高考（测试集），衡量一名学生的学业能力（机器的学习能力）  
在机器学习竞赛中，衡量模型的学习能力也是通过只进行一次测试（测试集）来打分的。  

In [5]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

data = load_breast_cancer()
X = data.data
y = data.target

X_temp1, X_test1, y_temp1, y_test1 = train_test_split(X, y, test_size=0.2, random_state=42)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_temp1, y_temp1, test_size=0.25, random_state=42)

print(f"数据总数: {len(X)}")
print(f"训练集(平时): {len(X_train1)}, 验证集(模拟考): {len(X_val1)}, 测试集(高考): {len(X_test1)}\n")

depth_options = [1, 5, 20]

best_score = 0
best_depth = 0

for depth in depth_options:
    model = RandomForestClassifier(max_depth=depth, random_state=42)
    model.fit(X_train1, y_train1)

    val_pred = model.predict(X_val1)
    val_score = accuracy_score(y_val1, val_pred)

    print(f"尝试树深度={depth} | 验证集(模拟考)得分: {val_score:.4f}")

    if val_score > best_score:
        best_score = val_score
        best_depth = depth

print(f"\n模拟考结束！我们选定最佳超参数：max_depth = {best_depth}")

final_model = RandomForestClassifier(max_depth=best_depth, random_state=42)
final_model.fit(X_temp1, y_temp1)

test_pred = final_model.predict(X_test1)
test_score = accuracy_score(y_test1, test_pred)

print(f"模型最终的测试集(高考)真实成绩是: {test_score:.4f}")

数据总数: 569
训练集(平时): 341, 验证集(模拟考): 114, 测试集(高考): 114

尝试树深度=1 | 验证集(模拟考)得分: 0.9561
尝试树深度=5 | 验证集(模拟考)得分: 0.9474
尝试树深度=20 | 验证集(模拟考)得分: 0.9474

模拟考结束！我们选定最佳超参数：max_depth = 1
模型最终的测试集(高考)真实成绩是: 0.9561
